def do_something():
    try:
        ...
    except ValueError as e:
        ...
    except UnicodeError as e:
        ...


def do_something_else():
    try:
        ...
    except [AttributeError, TypeError]:
        ...
